
<div class="col-md-2 col-sm-2 col-md-offset-1 box0" >
                  		<div class="box1">
					<span class="fa fa-check"></span>
					<h4>To Do List</h4>
                  		</div>
					  		
                  		</div>
                  	
                  		<div class="col-md-2 col-sm-2 box0">
                  			<div class="box1">
                                            <span class="fa fa-calendar"></span>
                                            <h4>Celendar</h4>
                  			</div>
					  			
                  		</div>
                  		<div class="col-md-2 col-sm-2 box0">
                  			<div class="box1">
					  			<span class="fa fa-bar-chart-o"></span>
					  			<h4>Chart</h4>
                  			</div>
					
                  		</div>
