
  <section class="wrapper" style="margin-top:0px;">
    <h3><i class="fa fa-tags" aria-hidden="true"></i>Your Tags </h3>
<?php if(isset($_SESSION['errtag'] )) echo $_SESSION['errtag'] ;?>
     <button type="button" class="btn btn-info " data-toggle="modal" data-target="#myModal" style="float:right; margin:-10px 20px 10px 0;">Create Tag</button>

<!-- Modal -->
<div class="modal fade" id="myModal" role="dialog">
<div class="modal-dialog">

<!-- Modal content-->
 <form action="<?php echo BASE_DIR?>index/addtags" method="post">
<div class="modal-content">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal">&times;</button>
    <h4 class="modal-title" style="color: #333333; font-weight: bolder;"><i class="fa fa-tags" aria-hidden="true"></i> Create Tag</h4>
  </div>
  <div class="modal-body">
        <span style="font-weight: bolder">Tag's Name: </span><input type="text" name="tag" id="tag" placeholder="Name Of Tags" minlength="3" style="border-radius: 5px; margin: 0 0 10px 40px;width: 400px;" required>
       
  </div>
  <div class="modal-footer">
    
    <button type="button" class="btn btn-default" data-dismiss="modal" id="btnadd">Close</button>
    <button type="submit" name="add" id="add" class="btn btn-dropbox">Create</button>
  </div>
</div>
       </form>

</div>

</div>



  <div class="row mt">
    <div class="col-lg-12">
              <div class="content-panel">
              <h4><i class="fa fa-angle-right"></i> List Tags</h4>
                  <section id="unseen">
                    <table class="display">
                      <thead>
                      <tr>
                          <th style="text-align: center;" class="numeric">Number</th>
                          <th style="text-align: center;" class="numeric">Name Of Tag</th>
                          <th style="text-align: center;" class="numeric">Select</th>
                      </tr>
                      </thead>
                      <tbody>
                      
               <?php 
               $stt=1;
               foreach($tag as $t)
               {
                    ?>
                        <tr>
                            <td style="text-align: center;"><?php echo $stt++;?></td>
                            <td style="text-align: center;"><?php echo $t['tentag'];?></td>
                            <td style="text-align: center;"> 
                                <a href='#' class="xoa" id="<?php echo $t['id']; ?>"> <i class="fa fa-trash-o" aria-hidden="true" style="font-size: 20px; color: red;"></i> </a>
                               &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                               <a data-toggle="modal" data-target="#<?php echo $t['id'];?>a" style="cursor: pointer;" > <i class="fa fa-cog" aria-hidden="true" style="font-size: 20px; color: #00c5de;"></i></a>
                                <div class="modal fade" id="<?php echo $t['id']; ?>a" role="dialog">
                                    <div class="modal-dialog">

                                        <!-- Modal content-->
                                        <form action="<?php echo BASE_DIR?>index/fixtag/<?php echo $t['id']; ?>" method="post">
                                            <div class="modal-content">
                                              <div class="modal-header">
                                                <button type="button" class="close" data-dismiss="modal">&times;</button>
                                                <h4 class="modal-title" style="color: #333333; font-weight: bolder;"><i class="fa fa-tags" aria-hidden="true"></i> Create Tag</h4>
                                              </div>
                                              <div class="modal-body">
                                                    <span style="font-weight: bolder">Tag's Name: </span><input type="text" name="tag" id="tag" value='<?php echo $t['tentag'] ?>' minlength="3" style="border-radius: 5px; margin: 0 0 10px 40px;width: 400px;" required>

                                              </div>
                                              <div class="modal-footer">

                                                <button type="button" class="btn btn-default" data-dismiss="modal" id="btnadd">Close</button>
                                                <button type="submit" name="add" id="add" class="btn btn-dropbox">Update</button>
                                              </div>
                                            </div>
                                        </form>

                                    </div>

                                </div>
                            </td>
                        </tr>
               <?php }?>
                  
                          
                     

                    
                      </tbody>
                  </table>
                  </section>
          </div><!-- /content-panel -->
       </div><!-- /col-lg-4 -->     
</div><!-- /row -->


</section>
<script>
$(document).ready(function() {
$('table.display').DataTable();
} );
</script>
<script>
                 $(document).ready(function() {
                    $(".xoa").click(function(){
                       var id = $(this).attr("id");
                       var hoi =confirm("Are you sure to delete??");
                       if(hoi==true)
                       {
                       window.location="<?php echo BASE_DIR?>index/xoatag/" +id;
                   }
                   else  return false;
                    });
                   
                 });
                        </script>
