<?php if(!isset($_SESSION['login_email'])) header('location:'. BASE_URL);
else
{?>

<!DOCTYPE html>
<?php 
date_default_timezone_set('Asia/Ho_Chi_Minh');
require_once 'PHPExcel/PHPExcel.php';
foreach($managetime as $t)
               {
                   $timeend = strtotime($t['timeend']);
                   $timenow = time();
                   $trangthai = $timeend -$timenow;
                   if ($trangthai<3600)
                   {
                       $trangthai2[] = $trangthai;
                   }
               }
               if(isset($trangthai2))
                {
                    $count = count($trangthai2);
                    $_SESSION['count'] = $count;
                }
                else $_SESSION['count'] = 0 ;

?>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="Dashboard">
    <meta name="keyword" content="Dashboard, Bootstrap, Admin, Template, Theme, Responsive, Fluid, Retina">

    <title>DASHGUM - FREE Bootstrap Admin Template</title>

    <!-- Bootstrap core CSS -->
    <link href="<?php echo BASE_DIR?>Public/assets/css/bootstrap.css" rel="stylesheet">
    <!--external css-->
    <script src="<?php echo BASE_DIR?>Public/assets/js/jquery.js"></script>

    <script src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
    <link href="<?php echo BASE_DIR?>Public/assets/font-awesome/css/font-awesome.css" rel="stylesheet" />
    <link rel="stylesheet" type="text/css" href="<?php echo BASE_DIR?>Public/assets/css/zabuto_calendar.css">
    <link rel="stylesheet" type="text/css" href="<?php echo BASE_DIR?>Public/assets/js/gritter/css/jquery.gritter.css" />
    <link rel="stylesheet" type="text/css" href="<?php echo BASE_DIR?>Public/assets/lineicons/style.css">    
    <link rel="stylesheet" href="http://cdn.oesmith.co.uk/morris-0.4.3.min.css">    
    <!-- Custom styles for this template -->
    <link href="<?php echo BASE_DIR?>Public/assets/css/style.css" rel="stylesheet">
    <link href="<?php echo BASE_DIR?>Public/assets/css/style-responsive.css" rel="stylesheet">
    <link href="<?php echo BASE_DIR?>Public/datatable/cssdatatable.css" rel="stylesheet">
    <script src="<?php echo BASE_DIR?>Public/assets/js/chart-master/Chart.js"></script>
    
    <!--to do list style -->
     <link href="<?php echo BASE_DIR?>Public/assets/css/style.css" rel="stylesheet">
    <link href="<?php echo BASE_DIR?>Public/assets/css/style-responsive.css" rel="stylesheet">
    <link rel="stylesheet" href="<?php echo BASE_DIR?>Public/assets/css/to-do.css">
    
    <script src="http://cdn.jsdelivr.net/webshim/1.12.4/extras/modernizr-custom.js"></script>
<!-- polyfiller file to detect and load polyfills -->
    <script src="http://cdn.jsdelivr.net/webshim/1.12.4/polyfiller.js"></script>
    
    
  </head>

  <body>

  <section id="container" >
      <!-- **********************************************************************************************************************************************************
      TOP BAR CONTENT & NOTIFICATIONS
      *********************************************************************************************************************************************************** -->
      <!--header start-->
      <header class="header black-bg">
              <div class="sidebar-toggle-box">
                  <div class="fa fa-bars tooltips" data-placement="right" data-original-title="Toggle Navigation"></div>
              </div>
            <!--logo start-->
            <a href="#" class="logo"><b>MNTIME <i class="fa fa-clock-o" aria-hidden="true"></i></b></a>
            <!--logo end-->
            <div class="nav notify-row" id="top_menu">
                <!--  notification start -->
                <ul class="nav top-menu">
                    <!-- settings start -->
                    <li class="dropdown">
                        <a data-toggle="dropdown" class="dropdown-toggle" href="index.html#">
                            <i class="fa fa-tasks"></i>
                            <span class="badge bg-theme"><?=$_SESSION['count']?></span>
                        </a>
                        <ul class="dropdown-menu extended tasks-bar">
                            <div class="notify-arrow notify-arrow-green"></div>
                            <li>
                                <p class="green">You have <?=$_SESSION['count']?> pending tasks</p>
                            </li>
                            <?php foreach($managetime as $t)
               {
                   $timeend = strtotime($t['timeend']);
                   $timenow = time();
                   $trangthai = $timeend -$timenow;
                    if ($trangthai<3600)
                    {
                   $time = floor((($trangthai)/60/60))." Hours ".Round((($trangthai)/60%60))." Mins";
                                ?>
                            <li>
                                <a href="index.html#">
                                    <div class="task-info">
                                        <div class="desc">TAG: <?php echo $t['tentag'];?></div>
                                        <div class="percent"><?=$time?></div>
                                    </div>
                                </a>
                            </li>
                    <?php }}?>

                            <li class="external">
                                <a href="#">See All Tasks</a>
                            </li>
                        </ul>
                    </li>
                    <!-- settings end -->
                </ul>
                <!--  notification end -->
            </div>
            <div class="top-menu">
            	<ul class="nav pull-right top-menu">
                    <li><a class="logout" href="<?=BASE_DIR?>index/logout">Logout</a></li>
            	</ul>
            </div>
        </header>
      <!--header end-->
      
      <!-- **********************************************************************************************************************************************************
      MAIN SIDEBAR MENU
      *********************************************************************************************************************************************************** -->
      <!--sidebar start-->
      <aside>
         <?php include 'View/function/menu.php';?>
      </aside>
      <!--sidebar end-->
      
      <!-- **********************************************************************************************************************************************************
      MAIN CONTENT
      *********************************************************************************************************************************************************** -->
      <!--main content start-->
      <section id="main-content">
          <section class="wrapper">
            
              <div class="row">
                  <div class="col-lg-9 main-chart">
                      <?php 
                      if($this->current_action=="trangchu") {?>
                  	<div class="row mtbox">
                  	 <?php include "View/function/mtbox.phtml"; ?>
                  	</div><!-- /row mt -->
                        
                        <div class="row mt">
                    
                         <?php include "View/function/todolist.phtml"; ?>
                        </div><!-- /row mt -->
                  
                        
                  </div><!-- /col-lg-9 END SECTION MIDDLE -->
                  
                  
      <!-- **********************************************************************************************************************************************************
      RIGHT SIDEBAR CONTENT
      *********************************************************************************************************************************************************** -->                  
              
                       <?php  include "View/function/notification.php";
                      } ?>
              </div>
                 <?php 
                 if($this->current_action=="managetag")include "View/function/todolistpage.phtml";
                 elseif($this->current_action=="managetime")include "View/function/managetime.php";
                 elseif($this->current_action=="workdone")include "View/function/workdone.php";
                 elseif($this->current_action=="report")include "View/function/report.php";
                 elseif($this->current_action=="export")include "View/function/export.php";
                ?>
          </section>
      </section>

      <!--main content end-->
      <!--footer start-->
      <footer class="site-footer">
          <div class="text-center">
              2014 - Alvarez.is
              <a href="index.html#" class="go-top">
                  <i class="fa fa-angle-up"></i>
              </a>
          </div>
      </footer>
      <!--footer end-->
  </section>

    <!-- js placed at the end of the document so the pages load faster -->
    
    
    
    
    <script src="<?php echo BASE_DIR?>Public/assets/js/bootstrap.min.js"></script>
    <script class="include" type="text/javascript" src="<?php echo BASE_DIR?>Public/assets/js/jquery.dcjqaccordion.2.7.js"></script>
    <script src="<?php echo BASE_DIR?>Public/assets/js/jquery.scrollTo.min.js"></script>
    <script src="<?php echo BASE_DIR?>Public/assets/js/jquery.nicescroll.js" type="text/javascript"></script>
    <script src="<?php echo BASE_DIR?>Public/assets/js/jquery.sparkline.js"></script>
    <script src="<?php echo BASE_DIR?>Public/datatable/datatable.js"></script>

    <!--common script for all pages-->
    
    <script type="text/javascript" src="<?php echo BASE_DIR?>Public/assets/js/gritter/js/jquery.gritter.js"></script>
    <script type="text/javascript" src="<?php echo BASE_DIR?>Public/assets/js/gritter-conf.js"></script>

    <!--script for this page-->
    <script src="<?php echo BASE_DIR?>Public/assets/js/sparkline-chart.js"></script>    
     <script src="<?php echo BASE_DIR?>Public/assets/js/zabuto_calendar.js"></script>	
     <!--script for todolist -->
    <script src="http://cdnjs.cloudflare.com/ajax/libs/raphael/2.1.0/raphael-min.js"></script>
    <script src="http://cdn.oesmith.co.uk/morris-0.4.3.min.js"></script>
    <script src="<?php echo BASE_DIR?>Public/assets/js/tasks.js" type="text/javascript"></script>
    <script src="<?php echo BASE_DIR?>Public/assets/js/morris-conf.js"></script>
    
    <script src="<?php echo BASE_DIR?>Public/assets/js/common-scripts.js"></script>
<!--	<script type="text/javascript">
        $(document).ready(function () {
        var unique_id = $.gritter.add({
            // (string | mandatory) the heading of the notification
            title: 'Welcome to Dashgum!',
            // (string | mandatory) the text inside the notification
            text: 'Hover me to enable the Close Button. You can hide the left sidebar clicking on the button next to the logo. Free version for <a href="http://blacktie.co" target="_blank" style="color:#ffd777">BlackTie.co</a>.',
            // (string | optional) the image to display on the left
            image: 'assets/img/ui-sam.jpg',
            // (bool | optional) if you want it to fade out on its own or just sit there
            sticky: true,
            // (int | optional) the time you want it to be alive for before fading out
            time: '',
            // (string | optional) the class name you want to apply to that specific message
            class_name: 'my-sticky-class'
        });

        return false;
        });
	</script>-->
	
<!--	<script type="application/javascript">
        $(document).ready(function () {
            $("#date-popover").popover({html: true, trigger: "manual"});
            $("#date-popover").hide();
            $("#date-popover").click(function (e) {
                $(this).hide();
            });
        
            $("#my-calendar").zabuto_calendar({
                action: function () {
                    return myDateFunction(this.id, false);
                },
                action_nav: function () {
                    return myNavFunction(this.id);
                },
                ajax: {
                    url: "show_data.php?action=1",
                    modal: true
                },
                legend: [
                    {type: "text", label: "Special event", badge: "00"},
                    {type: "block", label: "Regular event", }
                ]
            });
        });
        
        
        function myNavFunction(id) {
            $("#date-popover").hide();
            var nav = $("#" + id).data("navigation");
            var to = $("#" + id).data("to");
            console.log('nav ' + nav + ' to: ' + to.month + '/' + to.year);
        }
    </script>-->
        <script>
      jQuery(document).ready(function() {
          TaskList.initTaskWidget();
      });

      $(function() {
          $( "#sortable" ).sortable();
          $( "#sortable" ).disableSelection();
      });

    </script>
  </body>
</html>
<?php }?>